spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://192.168.99.100:5432/db" # on Windows
#    url: "jdbc:postgresql://127.0.0.1:5432/db" # on Linux
    username: "postgres"
    password: "123456"
  flyway:
    enabled: true
    schemas: public

# JWT Authentication
app:
  auth:
    jwtSecret: "MyJWTSuperMegaUltraExtraHyperOverSecretKey"
    jwtExpirationInMs: 604800000 # 7 days