spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://192.168.99.100:5432/db"
    username: "postgres"
    password: "123456"
  flyway:
    enabled: true
    schemas: public

# JWT Authentication
app:
  jwtSecret: "MyJWTSuperMegaUltraExtraHyperOverSecretKey"
  jwtExpirationInMs: 604800000 # 7 days